language: cpp
sudo: required
before_script:
    - chmod u+x *
script:
    - ./build.sh
branches:
    only:
        - master
addons:
    artifacts:
        paths:
            - object/out/*
        target_paths: travis-artifacts/$TRAVIS_BUILD_ID
    apt:
        packages:
            - gcc
            - g++
            - make
            - libc0.1-dev
            - g++-multilib
