language: generic
sudo: required
before_script:
    - chmod u+x *
    - ./download.sh
    - ./prerequisites.sh
script:
    - ./build.sh
branches:
    only:
        - master
        - test
addons:
    artifacts:
        paths:
            - object/out
            - logs
        target_paths: travis-artifacts/$TRAVIS_BUILD_ID
    apt:
        packages:
            - gcc
            - g++
            - make
            - gcc-multilib
            - g++-multilib
