language: cpp
sudo: required
before_script:
    - chmod u+x *
script:
    - travis_wait 720 ./build.sh
branches:
    only:
        - master
        - test
addons:
    artifacts:
        paths:
            - object/out
            - logs
        target_paths: travis-artifacts/$TRAVIS_BUILD_ID
    apt:
        packages:
            - gcc
            - g++
            - make
            - g++-multilib
